services:
  adminer:
    image: adminer:latest
    container_name: adminer_container
    ports:
      - "8080:8080"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_container
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      # Bind Mount (привязка данных в директории на ПК - контроль)
      - ./qdrant_storage:/qdrant/storage:z

  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_storage:/var/lib/postgresql/data:z

  # LangFuse
  my-text-to-sql-langfuse-postgres-1:
    image: docker.io/postgres:${POSTGRES_VERSION:-17}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: UTC
      PGTZ: UTC
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      # (Named Volume) - изолированное хранилище -  скорость
      - langfuse_postgres_data:/var/lib/postgresql/data

  my-text-to-sql-langfuse-web-1:
    image: langfuse/langfuse:2.60.0
    restart: always
    depends_on:
      my-text-to-sql-langfuse-postgres-1:
        condition: service_healthy
    environment:
      # Жестко прописываем подключение к вашему контейнеру langfuse-postgres
      - DATABASE_URL=postgresql://postgres:postgres@my-text-to-sql-langfuse-postgres-1:5432/postgres
      # ОБЯЗАТЕЛЬНО ДЛЯ V2: локальный адрес веб-интерфейса
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret_string_for_local_dev
      - SALT=salt_string_for_local_dev
      - TELEMETRY_ENABLED=false
    ports:
      - "0.0.0.0:3000:3000"

  agent:
    build: .  # Ищет Dockerfile в текущей корневой папке
    # image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    container_name: langgraph_agent
    # рабочую директорию внутри самого Docker-контейнера
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
    # Копируем файлы из корня проекта в раб директорию app контейнера
      - .:/app
      - /app/ui
      - /app/postgres_storage      # Скрываем бинарные данные PostgreSQL
      - /app/qdrant_storage        # Скрываем данные векторной базы Qdrant
      # Автономные тома для начального запуска (живут дольше контейнера)
      - agent_hf_cache:/root/.cache/huggingface
      - agent_fastembed_cache:/root/.cache/fastembed_cache
    env_file:
      - .env
    environment:
      - QDRANT_URL=http://qdrant:6333
      - PG_HOST=postgres
      # Указываем имя веб-сервиса Langfuse и его внутренний порт 3000
      - LANGFUSE_BASE_URL=http://my-text-to-sql-langfuse-web-1:3000
      - LANGFUSE_HOST=http://my-text-to-sql-langfuse-web-1:3000
      # Инструктируем библиотеки сохранять файлы строго по этим путям
      - HF_HOME=/root/.cache/huggingface
      - FASTEMBED_CACHE_PATH=/root/.cache/fastembed_cache
    command: uvicorn agent:app_fastapi --host 0.0.0.0 --port 8000 --reload
    # command: sh -c "uv sync && uv run uvicorn agent:app_fastapi --host 0.0.0.0 --port 8000 --reload"
    # command: sh -c "uv sync --frozen && uv run uvicorn agent:app_fastapi --host 0.0.0.0 --port 8000"

    depends_on:
      - postgres
      - qdrant
      # Агент ждет запуска веб-интерфейса Langfuse
      - my-text-to-sql-langfuse-web-1 
  # --- Next.js UI ---
  ui:
    # image: node:22-slim
    build: ./ui
    container_name: nextjs_ui
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./ui:/app
      # Docker полностью проигнорирует локальные node_modules и установит пакеты с нуля.
      - /app/node_modules
    environment:
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - SERVER_API_URL=http://agent:8000
    command: npm run dev
    depends_on:
      - agent

# объявления именованных томов (Named Volumes) для дальнейшего использования
volumes:
  langfuse_postgres_data:
  agent_hf_cache:
  agent_fastembed_cache: